ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "ingredientsPoints" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "clinicalNote" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "showClinicalNote" BOOLEAN NOT NULL DEFAULT false;
